name: TELF_conda
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.11.10
  - numpy<2.1.0
  - scipy
  - matplotlib
  - pathos
  - psutil
  - treelib
  - tqdm
  - gputil
  - pytest
  - scikit-learn
  - sparse
  - h5py
  - pandas
  - nltk
  - joblib
  - networkx
  - spacy
  - mat73
  - spacy-transformers
