name: TELF_conda
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.11.10
  - numpy<2.1.0
  - scipy
  - matplotlib
  - pathos
  - psutil
  - treelib
  - tqdm
  - gputil
  - pytest
  - scikit-learn
  - sparse
  - h5py
  - pandas
  - nltk
  - joblib
  - spacy
  - mat73
  - cupy
  - networkx
  - spacy-transformers
  - rapidfuzz
  - plotly
  - wordcloud
  - httpx
  - xmltodict
  - rbloom
  - pymongo
  - seaborn
  - umap-learn
  - pyvis
  - openai
  - langchain-ollama
  - transformers
  - torch