name: TELF_conda
channels:
  - conda-forge
  - conda
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pathos
  - psutil
  - treelib
  - tqdm
  - gputil
  - pytest
  - scikit-learn
  - sparse
  - h5py
  - pandas
  - nltk
  - joblib
  - spacy==3.7.2
  - mat73